services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DBNAME=myip
      - PG_USER=postgres
      - PG_PASSWORD=yourpassword
      - JWT_KEY=yourjwtkey
      - EMAIL_PASSWORD=yourgmailpassword
      - EMAIL=yourgmail
    depends_on:
      - db
    volumes:
      - .:/app  

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: myip
    ports:
      - "2468:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myip"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: